---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    install_recommends: false
    pkg:
      - curl
      - wget
      - unzip
