---
- name: Install sudo (Debian-like)
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Enable includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers file for the current user
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
